"""create corporate actions

Revision ID: 4695181a290e
Revises: 8c67240e250b
Create Date: 2026-08-26 20:24:11.146921

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4695181a290e"
down_revision: str | Sequence[str] | None = "8c67240e250b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("action_type", sa.String(length=16), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("split_ratio", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("dividend_amount", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("announced_at", sa.DateTime(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol",
            "action_type",
            "ex_date",
            "source",
            name="uq_corporate_actions_identity",
        ),
    )
    op.create_index(
        "ix_corporate_actions_symbol_ex_date",
        "corporate_actions",
        ["symbol", "ex_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_corporate_actions_symbol_ex_date", table_name="corporate_actions")
    op.drop_table("corporate_actions")
    # ### end Alembic commands ###
