"""create adjusted market bars

Revision ID: 51274cdec003
Revises: 4695181a290e
Create Date: 2026-08-26 20:33:54.585938

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51274cdec003"
down_revision: str | Sequence[str] | None = "4695181a290e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_bars_adjusted",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("timeframe", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("volume", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column(
            "adjustment_factor", sa.Numeric(precision=20, scale=12), nullable=False
        ),
        sa.Column("adjustment_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol",
            "timestamp",
            "timeframe",
            "source",
            "adjustment_version",
            name="uq_market_bars_adjusted_identity",
        ),
    )
    op.create_index(
        "ix_market_bars_adjusted_symbol_timestamp",
        "market_bars_adjusted",
        ["symbol", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_market_bars_adjusted_symbol_timestamp", table_name="market_bars_adjusted"
    )
    op.drop_table("market_bars_adjusted")
    # ### end Alembic commands ###
